-- seed_known_publishers.sql
-- Eenmalig uit te voeren in Supabase SQL Editor om de bekende-uitgevers-lijst te vullen.

INSERT INTO known_publishers (value) VALUES
    ('3 Park Square - Milton Park - Abingdon - Oxon - OX14 4RN - VK ; enquiries@taylorandfrancis.com'),
    ('Abbeville Press ; 655 Third Avenue - New York - NY 10017 - VS ; abbeville@abbeville.com'),
    ('Abrams ; 195 Broadway - 9th Floor - New York - NY 10007 - US ; abrams@abramsbooks.com'),
    ('ACC Art Books ; Riverside House - Dock Lane - Melton Woodbridge - Suffolk - IP12 1PE. - VK ; info@accartbooks.com'),
    ('Acco Learn ; Sluisstraat 10 - 3000 - Leuven - BE ; acco.be/contact/'),
    ('Adveniat ; Celsiusweg 41 - 8912 AM - Leeuwarden - NL ; info@adveniat.nl'),
    ('Allen Lane; One Embassy Gardens - 8 Viaduct Gardens - London - SW11 7BW - UK ; consumerservices@penguinrandomhouse.com'),
    ('Altamira ; Zijlweg 308 - 2015 CN - Haarlem - NL ; info@e-altamira.nl'),
    ('Ambo Anthos ; Weesperstraat 105A - 1018 VN - Amsterdam - NL ; info@amboanthos.nl'),
    ('Amphora Books ; Rapenburgerstraat 109 - 1011 VL - Amsterdam - NL ; info@amphorabooks.nl'),
    ('Amsterdam Boek ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; info@singeluitgeverijen.nl'),
    ('Angerenstein ; Postbus 2056 - 6802 CB - Arnhem - NL ; i.snippe@boom.nl'),
    ('AnkhHermes ; Herculesplein 96 - 3584 AA - Utrecht - NL ; ankh-hermes.nl/contact/'),
    ('Aperture ; 48 West 28th Street - 4th Floor - New York - NY 10001 - VS ; customerservice@aperture.org'),
    ('Aprilis uitgeverij Kimabo ; Markt 9 - 5301 AL - Zaltbommel - NL ; info@kimabo.nl'),
    ('Arbeiderspers ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; info@singeluitgeverijen.nl'),
    ('Archaia Studios Press ; 5670 Wilshire Blvd, Ste 400 - Los Angeles - CA 90036 - VS ; contact@boom-studios.com'),
    ('Archedigm ; 1230 Avenue of the Americas - New York - NY 10020 - VS ; Customerservicebiz@simonandschuster.com'),
    ('Archipel uitgeverij ; Wolvenstraat 40 - 9550 - Herzele - BE - info@uitgeverij-archipel.be'),
    ('Arena Editions ; Rottendorfer Straße 16 - 97074 Würzburg - DE ; arena-service@westermanngruppe.de'),
    ('Arenhövel ; Treuchtlinger Strasse 4 - 10779 - Berlijn - DE ; tanja.birkenstock@arena-verlag.de'),
    ('Areopagus ; Postbus 77 - 5126 ZH - Gilze - NL ; info@publishing.audax.nl'),
    ('Arnoud Voet ; Voorhaven 16 - 3024 RM Rotterdam - NL ; arnoudvoet@online.nl.'),
    ('Asoka ; Waarbekeplein 19 B - 9506 - Waarbeke - BE ; info@milinda.nl'),
    ('Aspekt - NL ;Amersfoortsestraat 27 - 3769 AD S- oesterberg NL; info@uitgeverijaspekt.nl'),
    ('Astraea ; Wateringsweg 34 - 3239 PO - Maastricht - NL ; https://www.uitgeverijastraea.nl/contact/'),
    ('Athenaeum ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; publiciteit@uitgeverijathenaeum.nl'),
    ('Atlas ; Weesperstraat 105-A - 1018 VN - Amsterdam - NL ; info@atlascontact.nl'),
    ('Atlas Contact ; Weesperstraat 105-A - 1018 VN - Amsterdam - NL ; info@atlascontact.nl'),
    ('Atrium ; Paladijnenweg 611 - 3813 KD - Amersfoort - NL ; info@t-atrium.nl'),
    ('Augustus ; Weesperstraat 105-A - 1018 VN - Amsterdam - NL ; info@atlascontact.nl'),
    ('AVVL (Arbeiders Vereniging Voor Lijkverbranding) ; Oude Stadsgracht 1 - 5611 DD - Eindhoven - NL ; info@yarden.nl'),
    ('B for Books ; Loosdrechtse Bos 19 - Dresselhuyspaviljoen 4-6 - 1213RH - Hilversum - NL ; info@b4books.nl'),
    ('Balans ; Keizersgracht 117 - 1015 CJ - Amsterdam - NL ; info@uitgeverijbalans.nl'),
    ('Barbican Cantre ; Silk Street - London - EC2Y 8DS - UK ; info@barbican.org.uk'),
    ('Bas Lubberhuizen ; Postbus 15511 - 1001 NA - Amsterdam - NL ; info@lubberhuizen.nl.'),
    ('Bataafsche Leeuw ; Rooseveltlaan 191-1 - 1079 BK - Amsterdam - NL ; http://bataafscheleeuw.nl/over-de-uitgeverij'),
    ('BBNC uitgevers ; Hoge Gouwe 93 - 2801 LD - Gouda - NL ; info@bbnc.nl'),
    ('Bdd Promotional Book Co ; 1540 BROADWAY NEW YORK NY - US ; info@bdd.com'),
    ('Becht ; Kabelweg 37 - 1014 BA - Amsterdam - NL ; info@harpercollins.nl'),
    ('Benerus ; Van Schoonbekestraat 36 - 2018 - Antwerpen - BE ; benerus@telenet.be'),
    ('Bernard & Graefe ; Heilsbachstraße 26 - 53123 - Bonn - DE ; info@moench-group.com'),
    ('Bert Bakker Prometeus ; Herengracht 48 - 1015 BN - Amsterdam - NL ; info@pbo.nl'),
    ('Best in Books ; Goorstraat 77 - 2560 - Nijlen - BE ; raffe.willems@telenet.be'),
    ('Big Tent Entertainment ; 216 West 18th street - New York - NY 10011 - VS ; info@bigtent.tv'),
    ('BIS Publishers BV ; Timorplein 46 - 1094 CC - Amsterdam - NL ; bis@bispublishers.com'),
    ('Blloan ; Franklin Rooseveltplaats 12 - 2060 - Antwerpen - Belgium ; info@standaarduitgeverij.be'),
    ('Bloomsbury ; 50 Bedford Square - Londen - WC1B 3DP - VK ; contact@bloomsbury.com'),
    ('Boekencentrum ; Herculesplein 96 - 3584 AA - Utrecht - NL ; info@kokboekencentrum.nl'),
    ('Boekerij Unieboek ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Bohn Stafleu van Loghum ; Varrolaan 114 - 3584 BW - Utrecht - NL ; klantenservice@bsl.nl'),
    ('Book Sales Inc ; 114 Northfield Ave.Edison NJ 08837 - US ; info@booksales.com'),
    ('Boom ; Stationsweg 66 - 7941 HG - Meppel - NL ; klantenservice@boom.nl'),
    ('Bosman ; Eernewoudeweg 2 - 6835 JG - Arnhem- NL ; info@bosmancommunicatie.nl'),
    ('BOSZ Art / Drukarnia BoSz / Wydawnictwo BoSzul ; Przemysłowa 1438-600 - Lesko - PL ; art@bosz.com.pl'),
    ('Bracken Books ; Pricess House - 50 Eastcastle Street - Londen - VK ; brackenbooks9@gmail.com'),
    ('Brandenburgisches Verlagshaus ; Dircksenstr. 48 - 10178 - Berlijn - DE ; info@edition-lempertz.de'),
    ('Briljant Boeken ; Hoogstraat 14 - 2851 BG - Haastrecht - NL ; team@briljantuitgeverij.nl'),
    ('Brittany Markert ; geen fysiek adres ; inroomsinfo@gmail.com'),
    ('Bruna Uitgevers, A.W. ; George Westinghousestraat 2 - 1097 BA - Amsterdam - NL ; info@awbruna.nl'),
    ('Bureau Oudheidkundig Onderzoek Rotterdam (BOOR) ; Schiekade 34 - 3032 AJ - Rotterdam - NL ; info@stichtingboor.nl'),
    ('Business Contact ; Weesperstraat 105A - 1017 VN - Amsterdam - NL ; start@businesscontact.nl'),
    ('Bzztoh ; Stille Veerkade 7 - 2512 BE - Den Haag - NL ; http://www.bzztoh.nl/contact/'),
    ('Callenbach ; Postbus 8049 - 3503 RA - Utrecht - NL ; info@vbku.nl'),
    ('Canongate ; 4 Uxbridge Street - Londen - W8 7SY - VK ; https://canongate.co.uk/contact/'),
    ('Cantecleer Kosmos ; Herculesplein 96 - 3584 AA - Utrecht - NL ; promotie@vbku.be'),
    ('Capitool ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Cargo ; Van Miereveldstraat 1-3 - 1071 DW - Amsterdam - NL ; info@uitgeverijcargo.nl'),
    ('Carice van Houten ; Biesbosch 30 - Amstelveen - 1181 JD - NL ; hello@keelian-mgmt.com'),
    ('Clavis ; Hellingbaan 422 - 1033 DB - Amsterdam. - NL ; info@clavisbooks.com'),
    ('ComicsOne ; 114 Northfield Ave.Edison NJ 08837 - US ; info@booksales.com'),
    ('Concertobooks ; Utrechtsestraat 52-60 - 1017 VP - Amsterdam - NL; info@concerto.nl'),
    ('ConferencePoint Verlag ; Dr. Almut Weinland - Distelkoppel 6 - D-22339 - Hamburg - De ; mail@conferencepoint.de'),
    ('Contact ; Weesperstraat 105-A - 1018 VN - Amsterdam - NL ; info@atlascontact.nl'),
    ('Corvina Verlag ; 1086 Budapest - Dankó utca 4-8 - HU ; corvina@lira.hu'),
    ('Cossee ; Kerkstraat 361 - 1017 HW - Amsterdam - NL ; http://www.uitgeverijcossee.nl/contact'),
    ('CPNB ; Prof. Tulpstraat 17 - 1018 GZ - Amsterdam - NL ; info@cpnb.nl'),
    ('Creapassions ; 148 Rue de l''université - 75007 - Parijs - FR ; diffusion@creapassions.com'),
    ('Createspace ; 7th Avenue - Seattle - WA 98121 - VS ; info@createspace.org'),
    ('Crown Publishers ; 1745 Broadway - Floor 13 - New York - NY 10019 - VS ; customerservice@prh.com'),
    ('Das Mag Uitgeverij ; Staalstraat 7A - 1011 JJ - Amsterdam - NL ; info@dasmag.nl'),
    ('Davidsfonds ; Sluisstraat 79 - bus 03.01 - 3000 - Leuven - BE ; info@davidsfonds.be'),
    ('De Bezige Bij ; Van Miereveldstraat 1 - 1071 DW - Amsterdam - NL ; info@debezigebij.nl'),
    ('De Fontein ; Postbus 13288 - 3507 LG - Utrecht - NL ; info@uitgeverijdefontein.nl'),
    ('De Geus ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; http://www.degeus.nl/contact/'),
    ('De Gulden Ster ; Weesperstraat 105A - 1018 VN - Amsterdam - NL ; info@atlascontact.nl'),
    ('De Harmonie ; Herengracht 555 - 1017BW - Amsterdam - NL ; info@deharmonie.nl'),
    ('De Jonge Hond ; postbus 1115 - 3840 BC - Harderwijk - NL ; info@jongehond.nl'),
    ('De Kern / De Fontein ; Postbus 13288 - 3507 LG - UTRECHT - NL ; info@uitgeverijdefontein.nl'),
    ('De Wakkere Muis ; Keizersgracht 6H - 1015 CN - Amsterdam - NL ; info@dewakkeremuis.nl'),
    ('De Zonnestraal ; Breelaan 56 - 1861 GG - Bergen - NL ; http://www.sonjabakker.nl/contact/'),
    ('Deboektant ; Oud-Cromstrijensedijk WZ 98 - 3286BV - Klaaswaal - NL ; info@deboektant.nl'),
    ('DeeTee Nederland ; Prinses Margrietplantsoen 118 - 1403TA - Bussum - NL ; info@deetee.nl'),
    ('Derrydale Books ; 4501 Forbes Blvd, Suite 200 - Lanham- MD 20706 - VS ; customercare@rowman.com'),
    ('Deutsches Historisches Museum ; Unter den Linden 2 - 10117 Berlijn - DE ;info@dhm.de'),
    ('Dewi Lewis Publishing ; 8 Broomfield Road Stockport SK4 4ND - UK ; mail@dewilewispublishing.com'),
    ('Die Gestalten Verlag ; Mariannenstraße 9–10 - 10999 - Berlijn - DE ; hello@gestalten.com'),
    ('Diergaarde Blijdorp ; Blijdorplaan 8 - 3041 JJ - Rotterdam - NL ; diergaardeblijdorp.nl/contact'),
    ('Distributed Art Pub Inc ; 75 Broad Street - Suite 630 - New York - NY 10004 - VS ; orders@dapinc.com'),
    ('Donker ; Kon. Emmaplein 1 - 3016 AA - Rotterdam - NL ; info@uitgeverijdonker.nl'),
    ('Double page ; 3 - rue Barbette - 75003 - Parijs - FR ; info@double-magazine.com'),
    ('Dumont ; Amsterdamer Straße 192 D50735 - Köln - DE ; info@dumont-buchverlag.de'),
    ('East-West Publications ; Anna Paulownastraat 78 - 2518 BJ - Den Haag - NL ; sufiap@hetnet.nl'),
    ('Edel SE & Co. KGaA ; Neumühlen 17 - 22763 - Hamburg - DE ; info@edel.com'),
    ('Éditions Casterman S.A. ; Rue Haute 139 - 1000 - Brussel - BE ; reception@casterman.com'),
    ('Éditions Du Chêne ; 58 rue Jean Bleuzen - 92170 - Vanves - FR ; https://www.editionsduchene.fr/contactez-nous/'),
    ('Éditions Milan ; 1 rond-point du Général Eisenhower - 31101- Toulouse - FR ; https://www.editionsmilan.com/contacts/'),
    ('Elesevier ; Radarweg 29 - 1043 NX - Amsterdam - NL ; http://elsevier.support/elsevier/contact'),
    ('Elmar ; Hoofdstraat 9 -2235 CA - Valkenburg - NL ; info@uitgeverijelmar.nl'),
    ('Europese Bibliotheek ; Amalialaan 126H - 3743 KJ - Baarn - NL ; info@europese-bibliotheek.nl'),
    ('Fairway ; Transistorstraat 80 - 1322 CH - Almere - NL ; klantenservice@intertaal.nl'),
    ('Fantagraphics ; 7563 Lake City Way - NE - Seattle - WA 98115 - VS ; helpme@fantagraphics.com'),
    ('Fibula-Van Dishoek ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Fontaine Uitgevers - Amstelplein 34 - 1096 BC - Amsterdam - NL ; info@fontaineuitgevers.nl'),
    ('Food Bai Food ; Leonardo da Vincilaan 3 bus 3 - 1930 - Zaventem - BE ; info@frixis.be'),
    ('Forte Uitgevers B.V. ; Postbus 684 - 3740 AP - Baarn - NL ; info@forteuitgevers.nl'),
    ('Forum ; Postbus 780 - 9700 AT Groningen - NL ; info@forum.nl'),
    ('Free Musketeers ; J.L. van Rijweg 74 - 2713 JA Zoetermeer - NL ; info@freemusketeers.nl'),
    ('Frimousse ; 8 rue de Ponthieu - 75008 Parijs - FR ; editions@frimousse.fr'),
    ('Futura ; Carmelite House - 50 Victoria Embankment - Londen - EC4Y 0DZ - VK ; LBBG.info@littlebrown.co.uk'),
    ('Gerard Wessel ; Gevers Deynootweg 82 - 2586BN - Den Haag - NL ; fotografie@gerardwessel.nl'),
    ('GESTO de Rolf Groep ; Mercuriusweg 14 - 4051 CV - Ochten - NL ; klantenservice@derolfgroep.nl'),
    ('Gottmer Uitgevers Groep ; Postbus 317 - 2000 AH - Haarlem - NL ; info@gottmer.nl'),
    ('Graauw''s uitgeversmaatschappij ; Singel 80 - Amsterdam - NL ; failliet in 1942'),
    ('Grand Central Publishing ; 1290 Avenue of the Americas - New York - NY 10104.- VS ; grandcentralpublishing@hbgusa.com'),
    ('Groen ; Celsiusweg 41 - 8912 AM - Leeuwarden - NL ; promotie@jongbloedmedia.nl'),
    ('Guest Editions ; Hackney Downs Studios - London - E8 2BT - VK ; studio@guesteditions.com'),
    ('Hachette ; 322 South Enterprise Blvd - Lebanon, IN 46052 - VS ; https://www.hachettebookgroup.com/landing-page/contact-us-2/'),
    ('Hado Publishing B.V. ; Herculesplein 96 - 3584 AA - Utrecht - NL ; http://www.ankh-hermes.nl/contact/'),
    ('Hancock House ; 19313 0 Avenue - Surrey, British Columbia - V3Z 9R9 - CA ; info@hancockhouse.com'),
    ('Hannibal ; Aerdtstraat 33 - 2060 - Antwerpen - BE ; gautier@hannibalbooks.be'),
    ('Hanze University of Applied Sciences - Groningen ; Zernikeplein 7 - 9747 AC Groningen - NL ; c.f.wind@hanze.nl'),
    ('Harlequin ; Kabelweg 37 - 1014 BA - Amsterdam - NL ; info@harpercollins.nl'),
    ('HarperCollins ; Kabelweg 37 - 1014 BA - Amsterdam - NL ; info@harpercollins.nl'),
    ('Hartmann books ; Liststrasse 28/1 - 70180 - Stuttgart - DE ; info@hartmannprojects.com'),
    ('Haystack, Uitgeverij ; De Nieuwe Erven 3-Unit 14098 - 5431 NV - Cuijk - NL ; needle@haystack.nl'),
    ('Heuff ; Laurierhof 8 - 1016 MA - Amsterdam - NL ; info@heuff.nl'),
    ('Hobby Hpuse ; Amplevine House- Dukes Road - Southampton SO14 0ST - VK ; info@hobbyhouse.com'),
    ('Hodder & Stoughton ; 322 South Enterprise Blvd - Lebanon, IN 46052 ; hachettebookgroup.com/-us-2/'),
    ('Holkema & Warendorf ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Hollandia ; Postbus 8049 - 3503 RA - Utrecht - NL ; info@vbku.nl'),
    ('House of Books ; Paul van Vlissingenstraat 18 - 1096 BK - Amsterdam - NL ; thehouseofbooks.com/contact.html'),
    ('Houtekiet Nederland ; Schaliënstraat 1 bus 11 - 2000 - Antwerpen - BE ; info@houtekiet.be'),
    ('HQN HarperCollins ; Kabelweg 37 - 1014 BA - Amsterdam - NL ; info@harpercollins.nl'),
    ('Humanitas ; Achillesstraat 290 - 3054 RL - Rotterdam - NL ; info@humanitas.nl'),
    ('HVC ; ''s-Gravenweg 327b - 2905 LB - Capelle aan den IJssel - NL ; info@hvc-capelle.nl'),
    ('ICOB ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('ImageBooks Factory B.V. ; Doornhoek 3742 - 5465 TA - Veghel - NL ; https://www.imagegroupholland.nl'),
    ('Inge van Iersel ; Wilgenlaan 21 - 5071CA - Udenhout ; info@ingevaniersel.com'),
    ('Inmerc ; Bruynvisweg 5 - 1531 AX - Wormer - NL ; https://inmerc.nl/contact/'),
    ('Instituut voor Biografiek ; Landgoed De Horst 1 - 7 Vossesteijn - 3971 KR - Driebergen-Rijsenburg ; contact@biografiek.nl'),
    ('Jan Anderson ; Kethelweg 50 - 3135 GM - Vlaardingen - NL ; https://www.jananderson.nl/contactformulier'),
    ('Jazzprezzo e.K. ; Geschwister-Scholl-Straße 16 - 32547 - Bad Oeynhausen - DE ; jazz@jazzprezzo.de'),
    ('Jessica Kingsley Publishers ; Carmelite House 50 Victoria Embankment London EC4Y 0DZ - UK ; hello@jkp.com'),
    ('Johan Mulder ; Oosthaven 28 - 2801 PD - Gouda - NL ; in 1957 failliet'),
    ('JOVIS Verlag ; Genthiner Str. 13 - 10785 Berlijn - DE; david.marold@degruyterbrill.com'),
    ('Just Publishers ; Sperwerkamp 10 - 3972 WE - Driebergen - NL ; bart@justpublishers.nl'),
    ('Kadmos ; Postbus 15138 - 3501 BC - Utrecht - NL ; http://elsevier.support/elsevier/contact'),
    ('Karakter Uitgevers ; George Westinghousestraat 2 - 1097 BA - Amsterdam - NL ; info@xanderuitgevers.nl'),
    ('Kehrer Verlag ; Rotebühlstraße 77 - 70178 - Stuttgart - DE ; https://www.kehrerverlag.com/en/contact/'),
    ('KIC, Uitgeverij ; Heiweg 168 - 6533 PG - Nijmegen - NL ; uitgeverij bestaat niet meer na het overlijden van Knoope'),
    ('Kimabo ; Markt 9 - 5301 AL - Zaltbommel - NL ; info@kimabo.nl'),
    ('Kluitman ; Schelphoek 2 - 1813 SE - Alkmaar - NL ; info@kluitman.nl'),
    ('KNLTB ; Bovenkerkerweg 81 - 1187 XC - Amstelveen - NL ; info!@knltb.nl'),
    ('Knopf Doubleday Publishing Group ; 1745 Broadway - New York - NY 10019 - VS ; info@penguinrandomhouse.com'),
    ('Kok Boekencentrum ; Herculesplein 96 - 3584 AA - Utrecht - NL ; info@kokboekencentrum.nl'),
    ('Koninklijke Vermande ; Maanweg 174 - 2516 AB - Den Haag - NL ; http://www.sdu.nl/service'),
    ('Kosmos ; Herculesplein 96 - 3584 AA - Utrecht - NL ; promotie@vbku.be'),
    ('Krikke CS ; Hoofdstraat 50 - 5109 AD - ''s Gravenmoer - NL ; info@krikkespecialbooks.nl'),
    ('Kwartier van Oisterwijk ; Sint Jorisstraat 7 - 5056 SB - Berkel-Enschot - NL ; kwartiervanoisterwijk@hotmail.com'),
    ('L.J. Veen ; Weesperstraat 105A - 1018 VN - Amsterdam - NL ; info@atlascontact.nl'),
    ('Landschap Noord Holland ; Postbus 222 - 1850 AE - Heiloo - NL info@landschapnoordholland.nl'),
    ('Lannoo ; Kasteelstraat 97 - B-8700 - Tielt - BE ; info@lannoo.be'),
    ('Lebowski Nederland ; Postbus 3626 - 1001 AK - Amsterdam NL; lebowskipublishers.nl/contact.html'),
    ('Lecturis ; ïstraat 2 - 5621 AE - Eindhoven - NL ; info@lecturis.nl'),
    ('Lemniscaat ; Vijverlaan 48 - 3062 HL - Rotterdam - NL ; info@lemniscaat.nl'),
    ('Leopold ; George Westinghousestraat 2- 1097 BA - Amsterdam - NL ; info@leopold.nl'),
    ('Lev uitgeverij ; Ossenwaard 2d - 3945PG - Cothen - NL ; info@boekenlev.nl'),
    ('Lias ; Mercatorstraat 63 – III -1056 PZ - Amsterdam - NL ; publiciteit@uitgeverijlias.nl'),
    ('Librero Nederland ; Hambakenwetering 8b - 5231 DC - ''s-Hertogenbosch - NL ; info@librero.nl'),
    ('List Verlag ; Goethestraße 43 - München 15 - DE ; sinds 1988 niet meer aktief'),
    ('Little Brown ; Carmelite House - 50 Victoria Embankment - Londen - EC4Y 0DZ - VK ; LBBG.info@littlebrown.co.uk'),
    ('Luitingh-Sijthoff ; Weesperstraat 105-A - 1018 VN - Amsterdam - NL ; info@lsuitgeverij.nl'),
    ('Luitingh-Sijthoff en Total Energies ; Weesperstraat 105-A - 1018 VN - Amsterdam - NL ; info@lsuitgeverij.nl'),
    ('MACK ; Studio E + B, Ground Floor - Emperor House - Dragonfly Place - Londen - SE4 2FL - VK ; support@mackbooks.co.uk'),
    ('Malmberg ; Magistratenlaan 138 - 5223 MB - ''s-Hertogenbosch - NL ; info@malmberg.nl'),
    ('Market Books ; Herculesplein 96 - 3584 AA - Utrecht - NL ; promotie@vbku.be'),
    ('Masterfoods/Mars ; Taylorweg 5 - 5466 AE - Veghel - NL ; info@marsverkoop.nl'),
    ('Maven Publishing ; Kromme Mijdrechtstraat 110-4 -1079 LD - Amsterdam - Nl ; info@mavenpublishing.nl'),
    ('Meddens ; Radarweg 29 - 1043 NX - Amsterdam - NL ; http://elsevier.support/elsevier/contact'),
    ('Mendo ; Nieuwe Doelenstraat 10 - 1012 CP - Amsterdam - NL ; service@mendo.nl'),
    ('Mets & Schilt ; Peter Martensstraat 121 - 1087 NA - Amsterdam - NL ; schilt@schiltpublishing.com'),
    ('Meulenhoff ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; info@meulenhoffboekerij.nl'),
    ('Ministerie van Economische Zaken ; Bezuidenhoutseweg 73 - 2594 AC - Den Haag - NL ; rijksoverheid.nl/contact/contactformulier'),
    ('Mo''Media ; Goudsesingel 68 - 3011 KD - Rotterdam - NL ; info@momedia.nl'),
    ('MoreThanWords BV ; Lange Boomgaardstraat 21 - 9000 - Gent - BE ; hans@mtw-morethanwords.nl'),
    ('Moussaults''s uitgeverij ; Franklin Rooseveltplaats 12 - 2060 - Antwerpen - BE ; info@standaarduitgeverij.be'),
    ('Muntinga ; Paul van Vlissingenstraat 18 - 1096 BK - Amsterdam - NL ; info@overamstel.com'),
    ('N.E.X.T. Company Publishers B.V.; Nieuwegracht 1a - 3763 LP - Soest - NL ; http:/www.nextcompany.nl/contact/'),
    ('nai010 ; Postbus 21927 - 3001 AX - Rotterdam - NL ; info@nai010.com'),
    ('Nauta, J ; Parkstraat 38 - 1791 CB - Texel (Den Burg) - NL ; info@nautaboek.nl'),
    ('Nederlands Politie Museum ; Postbus 3008 - 7303 GE - Apeldoorn - NL ; info@korpora.nl'),
    ('Nieuw Amsterdam ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; info@nieuwamsterdam.nl'),
    ('Nijgh & van Ditmar ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; publiciteit@nijghenvanditmar.nl'),
    ('Noordhoff Uitgevers ; Winschoterdiep 70a,- 9723 AB - Groningen - NL ; https://www.noordhoff.nl/klantenservice'),
    ('Northland Press ; Postbus N - Flagstaff - Arizona 86001 - VS ; news@northlandpress.com'),
    ('NZV ; Postbus 1492 -3800 BL - Amersfoort - NL ; info@kwintessens.nl'),
    ('Officine ; 20 B RUE LOUIS - PHILIPPE 92200 NEUILLY-SUR-SEINE - FR ; inof@semoffice.com'),
    ('Olli Gräf ; Auf der Taubenacht 4 - 55491 - Büchenbeuren - DE ; art@cosmotic.space'),
    ('Olympus ; Weesperstraat 105A - 1018 VN - Amsterdam - NL ; info@atlascontact.nl'),
    ('Omega ; Van Miereveldstraat 1-3 - 1071 DW - Amsterdam - NL ; info@uitgeverijcargo.nl'),
    ('Onomatopee office and project-space ; Lucas Gasselstraat 2a - 5613 LB - Eindhoven - NL ; info@onomatopee.net'),
    ('Oogachtend ; Hertogstraat 88/3 - 3001 - Heverlee BE ; ann@oogachtend.be'),
    ('Open Luchtmuseum ; Hoeferlaan 4 - 6816 SG - Arnhem - NL ; info@openluchtmuseum.nl'),
    ('Opportun ; 16 rue Dupetit-Thouars - 75003 - Paris - FR ; editionsopportun.com/contact'),
    ('Osho Publikaties ; Vianenstraat 48 - 106DD - Amsterdam - NL ; oshointernational@oshointernational.com'),
    ('Overamstel Uitgevers - Paul van Vlissingenstraat 18 - 1096 BK - Amsterdam - NL ; info@overamstel.com'),
    ('Oxford ; Great Clarendon Street - Oxford - OX2 6DP - VK ; primary.enquiries@oup.com'),
    ('P. Out ; HVKZ - Lagendijk 34 - 1541 KC - Koog aan de Zaan - NL ; info@historischeverenigingkoogzaandijk.n'),
    ('Pan MacMillan ; The Smithson - 6 Briset Street - Londen - EC1M 5NR- NL ; webqueries@macmillan.co.uk'),
    ('Panta Rhei ; Ligusterstraat 19 - 2225 RE - Katwijk aan Zee - NL ; pantarhei@wxs.nl'),
    ('Paragon Publishers ; 20-22 Wenlock Road - Londen - N1 7GU - VK ; nfo@paragonpublications.com.pk'),
    ('Paul Breuker ; Gorterplaats 2 - 6531 HZ - Nijmegen - NL ; info@paulbreuker.nl'),
    ('Pearsons ; Kabelweg 37 - 1014 BA - Amsterdam - NL ; klantenservice@pearson.com'),
    ('Penguin Books ; One Embassy Gardens - 8 Viaduct Gardens - London - SW11 7BW - UK ; consumerservices@penguinrandomhouse.com'),
    ('Peperoni Books ; Brunnenstraße 152 - 10115 Berlin - DE ; timeout@peperoni-books.de'),
    ('Petiet ; Lochemseweg 149 - 7217 RE - Harfsen - NL ; petiet@telez.fr'),
    ('Phaidon Press ; 65 Bleecker St. Fl 8. New York - NY 10012 - US ; customer.service@phaidon.com'),
    ('PHOENIX Opleidingen TA/NLP B.V. ; geen adres bekend ; http://www.phoenixopleidingen.nl/contact/'),
    ('Pictures Publishers ; Polstraat 52 - 4261 BV - Wijk en Aalburg - NL ; pictures.books@wxa.nl'),
    ('Plaschek, R. ; Pauwstraat 7 - 6811 GK - Arnhem - NL ; rens@plaschek.nl'),
    ('Ploegsma ; George Westinghousestraat 2 - 1097 BA - Amsterdam - NL ; info@ploegsma.nl'),
    ('Podium ; Postbus 15511- 1001 NA - Amsterdam - NL ; post@uitgeverijpodium.n'),
    ('Podium ; Willem Fenengastraat 2-a - 1096 BN - Amsterdam - NL ; post@uitgeverijpodium.nl'),
    ('Politie Rotterdam/Communicatie ; Doelwater 5 - 3011 AH - Rotterdam - NL ; mediadesk.rotterdam@politie.nl'),
    ('Postbus 3626 - 1001 AK - Amsterdam - NL ; info+inside@overamstel.com'),
    ('powerHouse Books ; 32 Adams Street - Brooklyn -, NY 11201 - VS ; publicity@powerHouseBooks.com'),
    ('Prentice Hall Direct Pearson Education ; Edinburgh Gate Harlow Essex CM20 2JE - UK ; info@phd.co.uk'),
    ('Princeton Architectural Press ; 70 West 36th Street - Floor 11 - New York - NY 10018 - VS ; https://papress.com/pages/contact-us'),
    ('Profiel ; Peizerweg 138 - 9727 AP - Groningen - NL ; info@profiel.nl'),
    ('Prometeus ; Herengracht 48 - 1015 BN - Amsterdam - NL ; info@pbo.nl'),
    ('Provincie Zeeland ; Postbus 6001 - 4330 LA - Middelburg - NL ; provincie@zeeland.nl'),
    ('Public Transformation ; Laan van Oversteen 18a, - 2289 CX - Rijswijk - NL ; info@publictransformation.eu'),
    ('Purple magazine ; rue Thérèse -75001 Parijs - FR ; inquire@purple.fr'),
    ('Q ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; https://www.singeluitgeverijen.nl/contact/'),
    ('Querido''s Uitgeverij ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; http://www.querido.nl/contact/'),
    ('Radius Books ; 227 East Palace Avenue, Suite W - Santa Fe - NM 87501 - VS ; info@radiusbooks.org'),
    ('Rainbow ; Paul van Vlissingenstraat 18 - 1096 BK - Amsterdam - NL ; info@rainbow.nl'),
    ('Random House ; One Embassy Gardens - 8 Viaduct Gardens - London - SW11 7BW - UK ; consumerservices@penguinrandomhouse.com'),
    ('Raum für Kunst, Aken ; der Sparkasse Aachen- Friedrich-Wilhelm-Platz 45 - 2062 - Aken - DE ; raum-fuer-kunst@euregiopost.de'),
    ('Rebo ; Arnoudstraat 14 - 2182 DZ - Hillegom - NL ; info@rebo-publishers.com'),
    ('Reco Multi Media ; Wilhelminalaan 38 - 9781 CW - Bedum - NL ; info@recomultimedia.nl'),
    ('Reel Art Press ; Office 4 - 61 Praed Street - Londen - W2 1NS - VK ; info@reelartpress.com'),
    ('Reflex ; Kaatstraat 20-24 - 3513 BK - Utrecht - NL ; hello@reflex-utrecht.com ·'),
    ('Regio Project ; Postbus 4010 - 9701 EA - Groningen - NL ; info@regio-project.org'),
    ('Regionaal Archief Rivierenland ; J.S. de Jongplein 3 - 4001 WG - Tiel - NL ; info@regionaalarchiefrivierenland.nl'),
    ('Ridge Press ; P.O. Box 61781 - Honolulu - Hawaii - 96839 - VS ; pr@ridge.com'),
    ('Rijksmuseum Van Oudheden ; Rapenburg 28 - 2311 EW - Leiden - NL ; info@rmo.nl'),
    ('ROSE stories ; Plantage Middenlaan 4-A - 1018 DD - Amsterdam - NL ; info@rosestories.nl'),
    ('Rowman & Littlefield ; 4501 Forbes Blvd, Suite 200 - Lanham- MD 20706 - VS ; customercare@rowman.com'),
    ('Rozekruis Pers ; Bakenessergracht 1 - 2011 JS - Haarlem - NL ; info@rozekruis.nl'),
    ('Samsara ; Herengracht 341 - 1016 AZ - Amsterdam - NL ; info@samsarabooks.com'),
    ('Schilt ; Peter Martensstraat 121 - 1087 NA - Amsterdam - NL ; schilt@schiltpublishing.com'),
    ('Schirmer/Mosel verlag ; Cuvilliésstr. 14 a - 81679 Munich - DE ; mail@schirmer-mosel.com'),
    ('Schocken Verlag ; Jerusalemer Straße 65/66, Berlijn - DE ; info@schockenverlag.de'),
    ('Scholten uitgeverij ; Katwolderweg 8 - 8041 AD - Zwolle - NL ; info@scholtenuitgeverij.nl'),
    ('Schors VOF ; Postbus 15624 - 1001 NC - Amsterdam - NL ; info@schors.nl'),
    ('Scratch Books ; Karthuizersplantsoen 14 - 1015 LS - Amsterdam - NL ; info@scratchbooks.nl'),
    ('Scriptum ; Tuinlaan 76 - 3111 AW - Schiedam - NL ; info@scriptum.nl'),
    ('SDU ; Maanweg 174 - 2516 AB - Den Haag - NL ; http://www.sdu.nl/service'),
    ('Servire ; Herculesplein 96 - 3584 AA - Utrecht - NL ; promotie@vbku.be'),
    ('Seuil ; 57 rue Gaston Tessier - 75019 - Parijs - FR ; contact@seuil.com'),
    ('Shambhala Publications Inc ; 2129 13th Street - Boulder -CO 80302 - VS ; support@shambhala.com'),
    ('Sijthoff ; Weesperstraat 105-A - 1018 VN - Amsterdam - NL ; info@lsuitgeverij.nl'),
    ('Simon & Schuster Ltd ; 99 Bishopsgate - Londen - EC2M 3TY - VK ; enquiries@simonandschuster.co.uk'),
    ('Singel Uitgeverijen Nederland ; Weteringschans 259 - 1017 XJ - Amsterdam - NL ; info@singeluitgeverijen.nl'),
    ('Singer Laren ; Oude Drift 1 - 1251 BS - Laren - NL ; museum@singerlaren.nl'),
    ('Sirene ; Nieuwezijds Voorburgwal 292 - 1012 RT - Amsterdam - NL ; info@mmpublications.com'),
    ('Spectacle Book Press; Überseering 33 - 5. Etage - 22297 Hamburg - DE ; bodeuxinternational.com/contact/'),
    ('Steidl ; Schweinfurthstraße 60 - 14195 - Berlijn - DE ; rights@steidl.de'),
    ('Stichting Aurora Borealis ; BusinessCenter The Rock - Atoomweg 6B - 9743AK - Groningen - NL ; info@stichtingborealis.nl'),
    ('Stichting Fotoboek Zaans Verzet ; Postbus 2000 - 1500 GA - Zaandam - NL ; postbus@zaanstad.nl'),
    ('Stichting Publicaties West-Alblasserwaard ; Cortgene 3 - 2951 EA - Alblasserdam - NL ; secretaris@hvwa.nl'),
    ('Stichting Sherpa ; Alleeweg 59 - 7521 VJ - Enschede - NL ; info@sherpa.nu.'),
    ('Stichting ''t Fiskershúske ; Fiskerspaad 4-8a - 9142 VN - Moddergat - NL ; info@museummoddergat.nl'),
    ('Stichting Verhalenhuis Belvédère ; Rechthuislaan 1 - 3072 LB - Rotterdam-Katendrecht - NL ; info@verhalenhuisbelvedere.nl'),
    ('Stichting Wilg & Mand ; Molenweg 54 - 6871 CX - Renkum - NL ; verenigingvanvlechters@gmail.com'),
    ('Stok ; Radarweg 29 - 1043 NX - Amsterdam - NL ; http://elsevier.support/elsevier/contact'),
    ('Strengholt ; Flevolaan 41 - 1411 KC - Naarden - NL ; info@strengholt.nl'),
    ('SUN ; Stationsweg 66 - 7941 HG - Meppel - NL ; klantenservice@boom.nl'),
    ('SWP Uitgeverij ; Spaklerweg 79-81 - 1114 AE - Amsterdam - NL ; klantenservice@mailswp.com'),
    ('Synthese ; Waarbekeplein 19 B - 9506 - Waarbeke - BE ; info@milinda.nl'),
    ('Taschen ; Hohenzollernring 53 - D50672 - Keulen ; contact@taschen.com'),
    ('Taylor & Francis ; 4 Park Square -Milton Park - Abingdon - Oxfordshire - OX14 4RN - VK ; enquiries@taylorandfrancis.com'),
    ('Teleboek ; Postbus 4 - 2400 MA - Alphen - NL ; info@wolterskluwer.com'),
    ('Ten Have ; Herculesplein 96 - 3584 AA - Utrecht - NL ; promotie@uitgeverijtenhave.nl'),
    ('Thames & Hudson ; 6–24 Britannia Street - London - WC1X 9JD - VK ; contact-us@thameshudson.co.uk'),
    ('The Eriskay Connection ; Nassausingel 26 - 4811 DG - Breda - NL ; mail@tecbooks.nl'),
    ('The Leasure Circle TLC ; York House - Empire Way - Wembley - Middlesex - HA9 0E - VK ; info@bertelsmann.com'),
    ('Thieme Meulenhoff; Smallepad 30 - 3811 MG - Amersfoort - NL ; info@thiememeulenhoff.nl'),
    ('Third Man Books ; 623 7th Avenue - South Nashville - TN 37203 - VS ; thirdmanbooks@thirdmanrecords.com'),
    ('TIEM ; Lingenstraat 9 - 8028 PM - Zwolle - BL ; info@tiem.nl'),
    ('Tirion ; Herculesplein 96 - 3584 AA - Utrecht - NL ; promotie@vbku.be'),
    ('TM uitgeverij ; Donauweg 10 - 1043 AJ - Amsterdam - NL ; tmuitgevers@xs4all.nl'),
    ('Torch Art Gallery ; Lauriergracht 94 - Amsterdam - NL ; hello@mynameissanderdekker.com'),
    ('Toth ; Nieuwe ''s-Gravelandseweg 3 - 1405 HH - Bussum - NL ; info@thoth.nl'),
    ('Trendboek ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Tresoar ; Boterhoek 1 - 8911 DH - Leeuwarden - NL ; info@tresoar.nl'),
    ('Trichis Publishing ; Goudsesingel 194-5e etage - 3011KD - Rotterdam - NL ; info@trichis.nl'),
    ('Twin Translations ; Missionstr 1 - Las Vegas - NV 89138 - VS ; judy.enner@twintranslations.com'),
    ('Uitgeverij Boekerij ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; info@meulenhoffboekerij.nl'),
    ('Uitgeverij de Verbeelding ; Sumatrakade 1425 - 1019RP - Amsterdam - NL ; ruudverkerk@kpnmail.nl'),
    ('Uitgeverij Digitalis ; Papiermolen 36 3994 DK - Houten - NL ; digitalis@digitalis.nl'),
    ('Uitgeverij Karnak ; Torenakker 6 - 6996 BD - Drempt - NL ; secretariaat@karnak.nl'),
    ('Uitgeverij Maarten Muntinga B.V. ; Herculesplein 96 - 3584 AA - Utrecht - NL ; promotie@vbku.be'),
    ('Uitgeverij Marmer ; Stationsplein 62 -3743 KM - Baarn - NL ; http://uitgeverijmarmer.nl/contact/'),
    ('Uitgeverij Noordboek ; Hellingbaas 1 - 8401 JH - Gorredijk - NL ; info@noordboek.nl'),
    ('Uitgeverij Oostland ; Mary Dresselhuysweg 54 - 2652 LD - Berkel en Rodenrijs - NL ; info@uitgeverijoostland.nl'),
    ('Uitgeverij Personalia ; Valge 3 - 9965 PD - Leens - NL ; info@uitgeverijpersonalia.nl'),
    ('Uitgeverij Roodbont - Postbus 4103 - 7200 BC - Zutphen - NL ; info@roodbont.nl'),
    ('Uitgeverij Signatuur ; George Westinghousestraat 2 - 1097 BA - Amsterdam - NL ; info@awbruna.nl'),
    ('Uitgeverij Sirius En Siderius ; Stalpertstraat 124 - 2597 RW - Den Haag - NL ; info@siriusensiderius.nl'),
    ('Uitgeverij Uquilair ; Biestkampweg 39 - 5249 JZ - Rosmalen - NL ; info@railmagazine.nl'),
    ('Uitgeverij Van Oorschot ; Herengracht 613 - 1017 CE - Amsterdam - NL ; contact@vanoorschot.nl'),
    ('Uitgeverij van Walraven ; Postbus 8049 - 3503 RA - Utrecht - NL ; info@vbku.nl'),
    ('Uitgeverij WBOOKS ; Boerendanserdijk 33A - 8024 AE - Zwolle - NL ; info@wbooks.com'),
    ('Unieboek ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Uniekboek Het Spectrum ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Uniekboek Het Spectrum Van Goor ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Uniekboek Het Spectrum Van Reenst ; Amstelplein 34 - 1096 BC - Amsterdam - NL; rights&contracts@unieboekspectrum.nl'),
    ('Uniepers ; Poolster 193 - 1622 EN - Hoorn - NL ; info@uniepersuitgevers.nl'),
    ('Utrechts Nieuwsblad ; Vredenburg 24 - 3511 BB - Utrecht - NL ; un.zuid@ad.nl'),
    ('Van Duuren Management ; Godfried Bomansstraat 7 - 4103 WR - Culemborg - NL ; http://www.vanduurenmedia.nl/Contact'),
    ('Van Gennep ; Verhoeksplein 2 (A-lab) -1031 KS - Amsterdam - NL ; info@vangennep-boeken.nl'),
    ('Van Goor ; Amstelplein 34 - 1096 BC - Amsterdam - NL ; rights&contracts@unieboekspectrum.nl'),
    ('Van Gorcum ; Dr. Nassaulaan 5 - 9401 HJ - Assen - NL ; uitgeverij@vangorcum.nl'),
    ('Van Kampen Standaard ; Franklin Rooseveltplaats 12 - 2060 - Antwerpen - BE ; info@standaarduitgeverij.be'),
    ('Van Reekummuseum CODA ; Vosselmanstraat 299 - 7311 CL Apeldoorn - NL ; mail@coda-apeldoorn.nl'),
    ('Van Reenst ; Amstelplein 34 - 1096 BC - Amsterdam - NL; rights&contracts@unieboekspectrum.nl'),
    ('Vassallucci ; Herengracht 48 - 1015 BN - Amsterdam - NL ; info@pbo.nl'),
    ('VDMS ; Broekerhavenweg 238 - 1611 CK - Bovenkarspel - NL ; https://www.motorsleepboot.nl/contact/'),
    ('Veen Bosch & Keuning Uitgeversgroep ; Postbus 8049 - 3503 RA - UTRECHT - NL ; info@vbku.nl'),
    ('Verbeek Boekproducties ; Niet meer actief ; Niet meer actief'),
    ('Vergaelen Nederland ; Sint-Katelijnestraat 63 - 2800 - Mechelen - BE ; info@standaarduitgeverij.be'),
    ('Verus ; Korenmolenlaan 2 - 3447 GG - Woerden - NL ; info@verus.nl'),
    ('Vita Feministische Uitgeverij ; Amstelplein 34 - 1096 BC - Amsterdam - NL; rights&contracts@unieboekspectrum.nl'),
    ('VNU ; Van der Madeweg 40 - 1114 AM - Amsterdam - NL ; info@dpgmedia.nl'),
    ('W.E.J. Tjeenk Willink ; Postbus 4 - 2400 MA - Alphen - NL ; info@wolterskluwer.com'),
    ('Waanders ; Faradaystraat 19 - 8013 PH - Zwoll - NL ; info@waanders.nl'),
    ('Wadwicht ; Bedumerweg 58 - 9959 PH - Onderdendam - NL ; contact@wadwicht.nl'),
    ('Walburg Pers ; Postbus 4159 - 7200 BD - Zutphen - NL ; info@walburgpers.nl.'),
    ('Warner Publishing ; 1290 Avenue of the Americas - New York - NY 10104.- VS ; grandcentralpublishing@hbgusa.com'),
    ('Watkins Media Limited Nederland ; Unit 11 Shepperton House 89 Shepperton Road London England N1 3DF - UK ; enquiries@watkinsmedia.org'),
    ('WATSON GUPTILL PUBN ; 165 W - 46th St - New York - New York, 10036 VS ; f.last@wgpub.com'),
    ('Wereldbibliotheek ; Amstelplein 34 - 1096 BC - Amsterdam - NL; info@wereldbibliotheek.nl'),
    ('Westfriesland Uitgeverij ; Herculesplein 96 - 3584 AA - Utrecht - NL ; info@kokboekencentrum.nl'),
    ('Wijnen, Uitgeverij Van ; Prins Hendrikkade 3A - 8801 JK - Franeker NL ; info@uitgeverijvanwijnen.n'),
    ('Willems Uitgevers ; Goorstraat 77 - 2560 - Nijlen - BE ; raffe.willems@telenet.be'),
    ('Windpferd KVG Kölner Verlagsgesellschaft mbH - Gutenbergstr. 33 D - 50823 - Keulen - DE ; https://www.windpferd.de/service/kontakt'),
    ('WLF Think Tank ; 30 N Gould Street - Sheridan - WY 82801 - VS ; info@101thingsatranslators.com'),
    ('Wolters Kluwer ; Postbus 4 - 2400 MA - Alphen - NL ; info@wolterskluwer.com'),
    ('Wolters Noordhof ; Winschoterdiep 70a,- 9723 AB - Groningen - NL ; https://www.noordhoff.nl/klantenservice'),
    ('Wyt ; Pieter de Hoochweg 111 - 3024 BG - Rotterdam - NL ; explore@wyt.nl'),
    ('Xander uitgevers ; George Westinghousestraat 2 - 1097 BA - Amsterdam - NL ; info@xanderuitgevers.nl'),
    ('Xavier Barral Editions ; 42 rue Sedaine - 75 011 - Parijs - FR ; exb@xavierbarral.fr'),
    ('Yale University Press ; P.O. Box 209040 - New Haven - CT 06520-9040 - VS ; yuppublicity@yale.edu'),
    ('ZEN Photo Gallery ; Piramide Bldg 2F - 6-6-9 Roppongi - Minato-ku - Tokyo - 106-0032 - JP ; info@zen-foto.jp'),
    ('Zie binnenzijde ; Vondelstraat 180 - 1054 GW - Amsterdam - NL ; lucy@ziebinnenzijde.nl'),
    ('Zirkoon ; Keizersgracht 6H - 1015 CN - Amsterdam - NL ; info@dewakkeremuis.nl'),
    ('Zomer & Keuning Uitgeversgroep ; Postbus 8049 - 3503 RA - Utrecht - NL ; info@vbku.nl'),
    ('Zoom ; Nijverheidsweg 18 - 2031 CP - Haarlem - NL ; info@zoom.nl'),
    ('Zuid-Hollandsche Uitgeversmaatschappij ; Radarweg 29 - 1043 NX - Amsterdam - NL ; http://elsevier.support/elsevier/contact'),
    ('Zuidnederlandse Uitgeverij ; Vluchtenburgstraat 7 - 2630 - Aartselaar - BE ; edi@znu.be.'),
    ('Zwerk uitgeverij ; Tuurdijk 16 - 3997 MS - ''t Goy-Houten - NL ; info@zwerkuitgevers.nl')
ON CONFLICT (value) DO NOTHING;
