"""
categories.py — Vaste dropdown-waarden voor category1 en (afhankelijk daarvan) category2,
zoals gebruikt op Boekwinkeltjes.

Elke lijst is een lijst van (waarde, label) tuples: 'waarde' is wat naar de API/database
gaat, 'label' is wat de gebruiker in de dropdown ziet.
"""

CATEGORY1_OPTIONS = [
    ("overig diverse", "overig"),
    ("detectives", "detectives"),
    ("geschiedenis", "geschiedenis"),
    ("hobby", "hobby"),
    ("kinderboeken", "kinderboeken"),
    ("literatuur", "literatuur"),
    ("literaire thriller", "literaire thriller"),
    ("psychologische thriller", "psychologische thriller"),
    ("kunst", "kunst"),
    ("romans", "romans"),
    ("jeugdroman", "jeugdroman"),
    ("science fiction fantasy", "science fiction fantasy"),
    ("strips", "strips"),
    ("studieboeken", "studieboeken"),
    ("topografie", "topografie"),
    ("toneel", "toneel cabaret muziek"),
]

_CATEGORY2_HOBBY = [
    ("", "Maak uw keuze"),
    ("afslanken", "Afslanken"),
    ("antiek", "Antiek"),
    ("astrologie", "Astrologie"),
    ("auto", "Auto"),
    ("bloemen", "Bloemen"),
    ("cartoons", "Cartoons"),
    ("dansen", "Dansen"),
    ("dieren", "Dieren"),
    ("ehbo", "Ehbo"),
    ("eten", "Eten"),
    ("Filatelie", "Filatelie"),
    ("film", "Film"),
    ("fotoboeken", "Fotoboek"),
    ("fotografie", "Fotografie"),
    ("gesteenten", "Gesteenten"),
    ("handwerken", "Handwerken"),
    ("huishouden", "Huishouden"),
    ("kaartspelen", "Kaartspelen"),
    ("kamperen", "Kamperen"),
    ("koninklijk huis", "Koninklijk huis"),
    ("kookboeken", "Kookboeken"),
    ("kunst", "Kunst"),
    ("kunstboeken", "Kunstboeken"),
    ("luchtvaart", "Luchtvaart"),
    ("magie", "Magie"),
    ("motor", "Motor"),
    ("natuur", "Natuur"),
    ("numismatiek", "Munten en briefgeld (Numismatiek)"),
    ("paarden", "Paarden"),
    ("pieck", "Pieck"),
    ("planten", "Planten"),
    ("poppen", "Poppen"),
    ("Postzegelsverzamelen", "Postzegelsverzamelen"),
    ("puzzelen", "Puzzelen"),
    ("reizen", "Reizen"),
    ("schaken", "Schaken"),
    ("schilderen", "Schilderen"),
    ("scouting", "Scouting"),
    ("spelen", "Spelen"),
    ("spoor- en tramwegen", "Spoor- en tramwegen"),
    ("sport", "Sport"),
    ("tekenen", "Tekenen"),
    ("televisie", "Televisie"),
    ("textiel", "Textiel"),
    ("treinen", "Treinen"),
    ("tuinieren", "Tuinieren"),
    ("verzorging", "Verzorging"),
    ("video", "Video"),
    ("vissen", "Vissen"),
    ("vliegtuigen", "Vliegtuigen"),
    ("vogels", "Vogels"),
    ("vrije tijd", "Vrije tijd"),
    ("watersport", "Watersport"),
    ("yoga", "Yoga"),
]

_CATEGORY2_STUDIEBOEKEN = [
    ("", "Maak uw keuze"),
    ("aardrijkskunde", "Aardrijkskunde"),
    ("administratie", "Administratie"),
    ("antropologie", "Antropologie"),
    ("archeologie", "Archeologie"),
    ("architectuur", "Architectuur"),
    ("astro", "Astro"),
    ("astronomie", "Astronomie"),
    ("automatisering", "Automatisering"),
    ("belasting", "Belasting"),
    ("beroepskeuze", "Beroepskeuze"),
    ("biologie", "Biologie"),
    ("communicatie", "Communicatie"),
    ("duits", "Duits"),
    ("economie", "Economie"),
    ("elektrotechniek", "Elektrotechniek"),
    ("emancipatie", "Emancipatie"),
    ("energie", "Energie"),
    ("engels", "Engels"),
    ("esoterie", "Esoterie"),
    ("expeditie", "Expeditie"),
    ("feminisme", "Feminisme"),
    ("filosofie", "Filosofie"),
    ("frans", "Frans"),
    ("genealogie", "Genealogie"),
    ("geografie", "Geografie"),
    ("geologie", "Geologie"),
    ("geschiedenis", "Geschiedenis"),
    ("gezondheidszorg", "Gezondheidszorg"),
    ("grafisch", "Grafisch"),
    ("informatica", "Informatica"),
    ("journalistiek", "Journalistiek"),
    ("Klassieke Talen", "Klassieke talen"),
    ("letteren", "Letteren"),
    ("luchtvaart", "Luchtvaart"),
    ("management", "Management"),
    ("marketing", "Marketing"),
    ("meteorologie", "Meteorologie"),
    ("milieu", "Milieu"),
    ("natuurkunde", "Natuurkunde"),
    ("nederlands", "Nederlands"),
    ("onderwijs", "Onderwijs"),
    ("opvoeding", "Opvoeding"),
    ("politiek", "Politiek"),
    ("psychiatrie", "Psychiatrie"),
    ("psychologie", "Psychologie"),
    ("rechten", "Rechten"),
    ("religie", "Religie"),
    ("scheikunde", "Scheikunde"),
    ("seksualiteit", "Seksualiteit"),
    ("sociale zekerheid", "Sociale zekerheid"),
    ("sociologie", "Sociologie"),
    ("spiritualiteit", "Spiritualiteit"),
    ("statistiek", "Statistiek"),
    ("sterrenkunde", "Sterrenkunde"),
    ("techniek", "Techniek"),
    ("theologie", "Theologie"),
    ("verpleging", "Verpleging"),
    ("verzorging", "Verzorging"),
    ("waterbouwkunde", "Waterbouwkunde"),
    ("wetenschap", "Wetenschap"),
    ("wiskunde", "Wiskunde"),
    ("woordenboek", "Woordenboek"),
]

_CATEGORY2_TOPOGRAFIE = [
    ("", "Maak uw keuze"),
    ("brabant", "Brabant"),
    ("drenthe", "Drenthe"),
    ("flevoland", "Flevoland"),
    ("friesland", "Friesland"),
    ("gelderland", "Gelderland"),
    ("groningen", "Groningen"),
    ("limburg", "Limburg"),
    ("noord-holland", "Noord-holland"),
    ("overijssel", "Overijssel"),
    ("utrecht", "Utrecht"),
    ("zeeland", "Zeeland"),
    ("zuid-holland", "Zuid-holland"),
    ("nederland", "Nederland"),
    ("benelux", "Benelux"),
    ("Nederlandse Antillen", "Nederlandse Antillen"),
    ("Curacao", "Curacao"),
    ("Belgie", "België"),
    ("bulgarije", "Bulgarije"),
    ("denemarken", "Denemarken"),
    ("duitsland", "Duitsland"),
    ("engeland", "Engeland"),
    ("Wales", "Wales"),
    ("Schotland", "Schotland"),
    ("finland", "Finland"),
    ("frankrijk", "Frankrijk"),
    ("griekenland", "Griekenland"),
    ("groenland", "Groenland"),
    ("hongarije", "Hongarije"),
    ("ierland", "Ierland"),
    ("italie", "Italië"),
    ("joegoslavie", "Joegoslavie"),
    ("noorwegen", "Noorwegen"),
    ("oostenrijk", "Oostenrijk"),
    ("polen", "Polen"),
    ("portugal", "Portugal"),
    ("rusland", "Rusland"),
    ("scandinavie", "Scandinavie"),
    ("spanje", "Spanje"),
    ("tsjechie", "Tsjechie"),
    ("turkije", "Turkije"),
    ("Zweden", "Zweden"),
    ("zwitserland", "Zwitserland"),
    ("europa", "Europa"),
    ("amerika", "Amerika"),
    ("australie", "Australië"),
    ("brazilie", "Brazilië"),
    ("canada", "Canada"),
    ("china", "China"),
    ("egypte", "Egypte"),
    ("india", "India"),
    ("indonesie", "Indië/Indonesië"),
    ("israel", "Israël"),
    ("japan", "Japan"),
    ("mexico", "Mexico"),
    ("nieuw-zeeland", "Nieuw-zeeland"),
    ("thailand", "Thailand"),
    ("tibet", "Tibet"),
    ("midden-oosten", "Midden-oosten"),
    ("Azie", "Azië"),
    ("afrika", "Afrika"),
    ("zuid-amerika", "Zuid-amerika"),
    ("noordpool", "Noordpool"),
    ("antarctica", "Zuidpool"),
    ("antarctica", "Antarctica"),
    ("wereld", "Wereld"),
]

CATEGORY2_OPTIONS = {
    "hobby": _CATEGORY2_HOBBY,
    "studieboeken": _CATEGORY2_STUDIEBOEKEN,
    "topografie": _CATEGORY2_TOPOGRAFIE,
}


def category1_label_for_value(value):
    for v, label in CATEGORY1_OPTIONS:
        if v == value:
            return label
    return value


def category2_label_for_value(category1_value, value):
    options = CATEGORY2_OPTIONS.get(category1_value, [])
    for v, label in options:
        if v == value:
            return label
    return value


# Engelse vertaling per label, voor gebruik bij het zoeken naar ISBNdb-subjects
# (die zijn doorgaans Engelstalig). Onbekende labels vallen terug op zichzelf.
ENGLISH_TRANSLATIONS = {
    # Categorie 1
    "overig": "other",
    "detectives": "detective fiction",
    "geschiedenis": "history",
    "hobby": "hobbies",
    "kinderboeken": "children's books",
    "literatuur": "literature",
    "literaire thriller": "literary thriller",
    "psychologische thriller": "psychological thriller",
    "kunst": "art",
    "romans": "novels",
    "jeugdroman": "young adult fiction",
    "science fiction fantasy": "science fiction fantasy",
    "strips": "comics",
    "studieboeken": "textbooks",
    "topografie": "topography",
    "toneel cabaret muziek": "theatre cabaret music",

    # Hobby
    "Afslanken": "weight loss",
    "Antiek": "antiques",
    "Astrologie": "astrology",
    "Auto": "automobiles",
    "Bloemen": "flowers",
    "Cartoons": "cartoons",
    "Dansen": "dancing",
    "Dieren": "animals",
    "Ehbo": "first aid",
    "Eten": "food",
    "Filatelie": "philately",
    "Film": "film",
    "Fotoboek": "photo book",
    "Fotografie": "photography",
    "Gesteenten": "rocks and minerals",
    "Handwerken": "handicrafts",
    "Huishouden": "household",
    "Kaartspelen": "card games",
    "Kamperen": "camping",
    "Koninklijk huis": "royal family",
    "Kookboeken": "cookbooks",
    "Kunstboeken": "art books",
    "Luchtvaart": "aviation",
    "Magie": "magic",
    "Motor": "motorcycles",
    "Natuur": "nature",
    "Munten en briefgeld (Numismatiek)": "numismatics",
    "Paarden": "horses",
    "Planten": "plants",
    "Poppen": "dolls",
    "Postzegelsverzamelen": "stamp collecting",
    "Puzzelen": "puzzles",
    "Reizen": "travel",
    "Schaken": "chess",
    "Schilderen": "painting",
    "Scouting": "scouting",
    "Spelen": "games",
    "Spoor- en tramwegen": "railways and tramways",
    "Sport": "sports",
    "Tekenen": "drawing",
    "Televisie": "television",
    "Textiel": "textiles",
    "Treinen": "trains",
    "Tuinieren": "gardening",
    "Verzorging": "personal care",
    "Video": "video",
    "Vissen": "fishing",
    "Vliegtuigen": "airplanes",
    "Vogels": "birds",
    "Vrije tijd": "leisure",
    "Watersport": "water sports",
    "Yoga": "yoga",

    # Studieboeken
    "Aardrijkskunde": "geography",
    "Administratie": "administration",
    "Antropologie": "anthropology",
    "Archeologie": "archaeology",
    "Architectuur": "architecture",
    "Astro": "astro",
    "Astronomie": "astronomy",
    "Automatisering": "automation",
    "Belasting": "tax",
    "Beroepskeuze": "career choice",
    "Biologie": "biology",
    "Communicatie": "communication",
    "Duits": "german",
    "Economie": "economics",
    "Elektrotechniek": "electrical engineering",
    "Emancipatie": "emancipation",
    "Energie": "energy",
    "Engels": "english",
    "Esoterie": "esotericism",
    "Expeditie": "expedition",
    "Feminisme": "feminism",
    "Filosofie": "philosophy",
    "Frans": "french",
    "Genealogie": "genealogy",
    "Geografie": "geography",
    "Geologie": "geology",
    "Gezondheidszorg": "healthcare",
    "Grafisch": "graphic design",
    "Informatica": "computer science",
    "Journalistiek": "journalism",
    "Klassieke talen": "classical languages",
    "Letteren": "humanities",
    "Management": "management",
    "Marketing": "marketing",
    "Meteorologie": "meteorology",
    "Milieu": "environment",
    "Natuurkunde": "physics",
    "Nederlands": "dutch",
    "Onderwijs": "education",
    "Opvoeding": "parenting",
    "Politiek": "politics",
    "Psychiatrie": "psychiatry",
    "Psychologie": "psychology",
    "Rechten": "law",
    "Religie": "religion",
    "Scheikunde": "chemistry",
    "Seksualiteit": "sexuality",
    "Sociale zekerheid": "social security",
    "Sociologie": "sociology",
    "Spiritualiteit": "spirituality",
    "Statistiek": "statistics",
    "Sterrenkunde": "astronomy",
    "Techniek": "technology",
    "Theologie": "theology",
    "Verpleging": "nursing",
    "Waterbouwkunde": "hydraulic engineering",
    "Wetenschap": "science",
    "Wiskunde": "mathematics",
    "Woordenboek": "dictionary",

    # Topografie
    "Noord-holland": "north holland",
    "Zuid-holland": "south holland",
    "Nederland": "netherlands",
    "Benelux": "benelux",
    "Nederlandse Antillen": "netherlands antilles",
    "Curacao": "curacao",
    "België": "belgium",
    "Bulgarije": "bulgaria",
    "Denemarken": "denmark",
    "Duitsland": "germany",
    "Engeland": "england",
    "Wales": "wales",
    "Schotland": "scotland",
    "Finland": "finland",
    "Frankrijk": "france",
    "Griekenland": "greece",
    "Groenland": "greenland",
    "Hongarije": "hungary",
    "Ierland": "ireland",
    "Italië": "italy",
    "Joegoslavie": "yugoslavia",
    "Noorwegen": "norway",
    "Oostenrijk": "austria",
    "Polen": "poland",
    "Rusland": "russia",
    "Scandinavie": "scandinavia",
    "Spanje": "spain",
    "Tsjechie": "czech republic",
    "Turkije": "turkey",
    "Zweden": "sweden",
    "Zwitserland": "switzerland",
    "Europa": "europe",
    "Amerika": "america",
    "Australië": "australia",
    "Brazilië": "brazil",
    "Egypte": "egypt",
    "Indië/Indonesië": "india/indonesia",
    "Israël": "israel",
    "Nieuw-zeeland": "new zealand",
    "Midden-oosten": "middle east",
    "Azië": "asia",
    "Afrika": "africa",
    "Zuid-amerika": "south america",
    "Noordpool": "north pole",
    "Zuidpool": "south pole",
    "Wereld": "world",
}


def english_translation(label):
    """Geeft de Engelse vertaling van een categorielabel, of het label zelf als die onbekend is."""
    return ENGLISH_TRANSLATIONS.get(label, label)
